deployment:
  # image: "ghcr.io/hritvikpatel4/apache-atlas"
  image: "apache-atlas"
  tag: "2.2.0-test"
  replicas: 1

config_name: atlasconfig
active_instance_name: apache-atlas-active
passive_instance_name: apache-atlas-passive
active_instance_name_fqdn: apache-atlas-active.default.svc.cluster.local
passive_instance_name_fqdn: apache-atlas-passive.default.svc.cluster.local

create_solr_indices: 
  key: "CREATE_SOLR_INDICES"
  value: "no"

graph_storage_lock_wait_time: 
  key: "GRAPH_STORAGE_LOCK_WAIT_TIME"
  value: 10000
solr_zookeeper_connect_timeout:  
  key: "SOLR_ZOOKEEPER_CONNECT_TIMEOUT"
  value: 600000
solr_zookeeper_session_timeout:  
  key: "SOLR_ZOOKEEPER_SESSION_TIMEOUT"
  value: 600000

kafka_zookeeper_session_timeout:  
  key: "KAFKA_ZOOKEEPER_SESSION_TIMEOUT"
  value: 60000
kafka_zookeeper_connection_timeout:  
  key: "KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT"
  value: 30000
kafka_zookeeper_sync_time:  
  key: "KAFKA_ZOOKEEPER_SYNC_TIME"
  value: 20
kafka_auto_commit_interval:  
  key: "KAFKA_AUTO_COMMIT_INTERVAL"
  value: 1000

audit_zookeeper_session_timeout:  
  key: "AUDIT_ZOOKEEPER_SESSION_TIMEOUT"
  value: 10000

ha_zookeeper_retry_sleeptime:  
  key: "HA_ZOOKEEPER_RETRY_SLEEPTIME"
  value: 1000
ha_zookeeper_session_timeout:  
  key: "HA_ZOOKEEPER_SESSION_TIMEOUT"
  value: 300000
client_ha_sleep_interval:  
  key: "CLIENT_HA_SLEEP_INTERVAL"
  value: 5000

ha:
  address:
    server1: "SERVER1_ADDR"
    server2: "SERVER2_ADDR"

service:
  port_type: NodePort
  ports:
    target_port: 21000
    active_port: 31002
    passive_port: 31003

container:
  args1: "cold_start"
  args2: "--ha"
  resources:
    memory: "4Gi"
    cpu: "2"
  hostname:
    hostname: "HOSTNAME"
    active: "ACTIVE_HOSTNAME"
    passive: "PASSIVE_HOSTNAME"
    solr:
      host:
        key: "SOLR_HOST"
        value: "192.168.0.153"
      port:
        key: SOLR_PORT
        value: "8983"
  ports:
    container_port: 21000
  env_vars:
    hbase:
      table:
        key: "HBASE_TABLE"
        value: "apache_atlas_janus"
    kafka:
      bootstrap_servers:
        key: "KAFKA_BOOTSTRAP_SERVERS"
        value: "192.168.0.151:9092"
    zookeepers_quorum:
      hbase: 
        key: "HBASE_ZK_QUORUM"
        value: "192.168.0.151:2181"
      solr: 
        key: "SOLR_ZK_QUORUM"
        value: 192.168.0.151:2181\/solr
      kafka: 
        key: "KAFKA_ZK_QUORUM"
        value: 192.168.0.151:2181\/kafka
      atlas:
        key: "ATLAS_ZK_QUORUM"
        value: 192.168.0.151:2181
  hostAliases:
    hosts:
      ip1: "192.168.0.151"
      name1: "node101.bigdata.com"
      ip2: "192.168.0.152"
      name2: "node102.bigdata.com"
      ip3: "192.168.0.153"
      name3: "node103.bigdata.com"
      ip4: "192.168.0.154"
      name4: "node104.bigdata.com"
