apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  namespace: default
  labels:
    name: busybox1
spec:
  containers:
  - name: busybox1
    image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  
  restartPolicy: Always
