---
- name: Configuring Apache Hadoop Commons
  hosts: all
  become: true

  tasks:
    - name: Printing Variables
      debug:
        msg: "Hadoop Home - {{ HADOOP_HOME }}, TMP Dir - {{ HADOOP_TMP_DIR }}"
    - name: Configuring core-site.xml
      blockinfile:
        path: '{{ HADOOP_HOME }}/etc/hadoop/core-site.xml'
        insertafter: <configuration>
        block: |2
            <property>
              <name>hadoop.tmp.dir</name>
              <value>{{ HADOOP_TMP_DIR }}</value>
            </property>
            <property>
              <name>fs.default.name</name>
              <value>hdfs://{{ namenode }}:9000</value>
            </property>
        state: present
        backup: true