---
- name: Configuring Apache Hadoop Datanode Service
  hosts: "{{ servers }}"
  become: true

  tasks:
    - name: Creating Hadoop data directories
      file:
        path: "{{ HADOOP_DATANODE_DATA_DIR }}"
        state: directory
        mode: 0775

    - name: Configuring hdfs-site.xml
      blockinfile:
        path: '{{ HADOOP_HOME }}/etc/hadoop/hdfs-site.xml'
        insertafter: <configuration>
        block: |2
            <property>
              <name>dfs.namenode.name.dir</name>
              <value>{{ HADOOP_NAMENODE_DATA_DIR }}</value>
            </property>
            <property>
              <name>dfs.datanode.data.dir</name>
              <value>{{ HADOOP_DATANODE_DATA_DIR }}</value>
            </property>
            <property>
              <name>dfs.namenode.checkpoint.dir</name>
              <value>{{ HADOOP_CHECKPOINT_DATA_DIR }}</value>
            </property>
            <property>
              <name>dfs.replication</name>
              <value>{{ HADOOP_REPLICATION_FACTOR }}</value>
            </property>
            <property>
              <name>dfs.namenode.datanode.registration.ip-hostname-check</name>
              <value>{{ HADOOP_HOSTNAME_CHECK }}</value>
            </property>
        state: present
        backup: true