# (try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
# dnf distro-sync -y --allowerasing --skip-broken --nobest
---
- name: Install Python3 on CentOS 8
  hosts: localservers
  become: yes

  tasks:
    - name: Upgrade all packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Installing Python 3.9
      dnf:
        name: python39
        state: present