---
  - name: install-apache-server-playbook
    hosts: myservers
    become: yes
    become_user: root
    tasks:
      - name: Ensure Apache Server is at the latest version
        yum:
          name: httpd
          state: latest
      
      - name: Ensure Apache Server is running
        service:
          name: httpd
          state: started

      - name: Copy index.html
        copy:
          src: index.html
          dest: /var/www/html/
          owner: root
          group: root
          mode: 0644
        notify: restart apache

      - name: Add http firewall rule
        firewalld:
          service: http
          permanent: yes
          state: enabled

      - name: Add https firewall rule
        firewalld:
          service: https
          permanent: yes
          state: enabled
