---
- name: install-nginx-server
  hosts: myservers
  become: yes
  become_user: root
  tasks:
    - name: Install EPEL Release
      yum:
        name: epel-release

    - name: Ensure NGINX Server is at the latest version
      yum:
        name: nginx
        state: latest

    - name: Ensure NGINX Server is running
      service:
        name: nginx
        state: started

    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted