---
- name: Setup Environment Variables
  hosts: myservers

  tasks:

    # - name: Setting up JAVA_HOME HADOOP_HOME and PATH
    #   lineinfile:
    #     dest: /etc/profile
    #     line: '{{ item }}'
    #     state: present
    #   with_items:
    #     - ' '
    #     - 'export JAVA_HOME=/usr/lib/jvm/java'
    #     - 'export HADOOP_HOME=/usr/local/hadoop'
    #     - 'export PATH=$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin'

    - name: Remove unused environment variables
      lineinfile:
        path: /etc/profile
        regexp: "(.*)_HOME"
        state: absent

    - name: Setting up JAVA_HOME HADOOP_HOME and PATH
      lineinfile:
        dest: /etc/profile
        state: present
        insertafter: EOF
        line: |
    
          export JAVA_HOME=/usr/lib/jvm/java
          export HADOOP_HOME=/usr/local/hadoop
          export PATH=$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin