apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeepervolume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "hostpath"
  hostPath:
    path: "/zookeeper"
