apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper-service
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
    name: client
  - protocol: TCP
    port: 2888
    name: follower
    targetPort: 2888
  - protocol: TCP
    port: 3888
    targetPort: 3888
    name: leader