apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    run: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: webapp
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USER
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_URL

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    run: webapp
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 31000       # This port is for External Service
    
