# Default values for hello-spring-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: ashokkumarchoppadandi/hello-spring-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2.0"

resources:
  cpu: 1
  memory: 512Mi

service:
  type: NodePort
  port: 8080
  nodePort: 31000

configmap:
  app:
    version: v2