apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: HelloApp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: hello-external-service
spec:
  type: NodePort
  selector:
    app: HelloApp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
