apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: ClusterIP
  selector:
    app: hello-word-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080