apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
spec:
  selector:
    matchLabels:
      name: web-application
  template:
    metadata:
      labels:
        name: web-application
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
            requests:
              cpu: "100m"
              memory: "50Mi"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-application-service
spec:
  type: ClusterIP
  selector:
    name: web-application
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-application
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20

