apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-node-port
spec:
  type: NodePort
  selector:
    app: hello-word-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007