apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: simple-pod
spec:
  containers:
  - name: simple-pod1
    image: alpine
    command:
      - sh
      - -c
      - 'echo This is first container; sleep 3600'
    resources:
      limits:
        memory: "50Mi"
        cpu: "100m"
    volumeMounts:
      - mountPath: /pod-volume1
        name: empty-dir-volume
  
  - name: simple-pod2
    image: alpine
    command:
      - sh
      - -c
      - 'echo This is second container; sleep 3600'
    resources:
      limits:
        memory: "50Mi"
        cpu: "100m"
      requests:
        memory: "50Mi"
        cpu: "100m"
    volumeMounts:
      - mountPath: /pod-volume2
        name: empty-dir-volume
  
  - name: simple-pod3
    image: alpine
    command:
      - sh
      - -c
      - 'echo This is third container; sleep 3600'
    resources:
      limits:
        memory: "50Mi"
        cpu: "100m"
      requests:
        memory: "50Mi"
        cpu: "100m"
    volumeMounts:
      - mountPath: /pod-volume3
        name: empty-dir-volume

  volumes:
    - name: empty-dir-volume
      emptyDir: {}