---
- name: Install and Configure Apache Hadoop MR History Server Service
  hosts: mrhistoryservers
  become: true

  vars:
    HADOOP_NAMENODE_HOSTNAME: dockermachine1.bigdata.com
    HADOOP_HISTORY_SERVER_HOSTNAME: dockermachine1.bigdata.com
    HADOOP_VERSION: 2.8.0
    HADOOP_HOME: /usr/local/hadoop
    HADOOP_TMP_DIR: /usr/local/hadoop/data/tmp
    HADOOP_NAMENODE_DATA_DIR: /usr/local/hadoop/data/namenode
    HADOOP_DATANODE_DATA_DIR: /usr/local/hadoop/data/datanode
    HADOOP_CHECKPOINT_DATA_DIR: /usr/local/hadoop/data/namesecondary
    HADOOP_REPLICATION_FACTOR: 1
    HADOOP_HOSTNAME_CHECK: 'false'
    HADOOP_MAPREDUCE_FRAMEWORK_NAME: yarn
    HADOOP_YARN_NODEMANAGER_RESOURCE_MEMORY_MB: 4096
    HADOOP_YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: 4096
    HADOOP_YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: 512
    HADOOP_YARN_NODEMANAGER_VMEM_CHECK_ENABLED: 'false'
    HADOOP_YARN_APP_MAPREDUCE_AM_RESOURCE_MB: 512
    HADOOP_YARN_APP_MAPREDUCE_AM_COMMAND_OPTS: '-Xmx2048m'
    HADOOP_MAPREDUCE_MAP_CPU_VCORES: 1
    HADOOP_MAPREDUCE_REDUCE_CPU_VCORES: 1
    HADOOP_MR_HISTORY_SERVER_SERVICE_FILE: /etc/systemd/system/mrhistoryserver.service

  tasks:
    - name: Get Hostname
      command: hostname -f
      register: hostname_fqdn

    - name: Print Message
      debug:
        msg: 'Installing MR History Server on host: {{ hostname_fqdn.stdout }}'

    - name: Upgrade OS Packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Create SSH config file
      file:
        path: ~/.ssh/config
        state: touch

    - name: Disable Strict Host Key Checking
      copy:
        dest: ~/.ssh/config
        content: |
          Host *
            UserKnownHostsFile /dev/null
            StrictHostKeyChecking no
            LogLevel quiet
            Port 2122

    - name: Set Permissions for Config file
      file:
        path: ~/.ssh/config
        owner: root
        group: root
        mode: 0400
        state: file

    - name: Install Open JDK 8
      dnf:
        name: java-1.8.0-openjdk-devel
        state: present

    - name: Download and Untar Apache Hadoop
      unarchive:
        src: 'https://archive.apache.org/dist/hadoop/hadoop-{{ HADOOP_VERSION }}.tar.gz'
        dest: '/usr/local'
        remote_src: yes
        creates: '/usr/local/hadoop-{{ HADOOP_VERSION }}'

    - name: Create Hadoop Directory Soft Link
      file:
        src: '/usr/local/hadoop-{{ HADOOP_VERSION }}'
        dest: '{{ HADOOP_HOME }}'
        state: link

    - name: Setting up JAVA_HOME HADOOP_HOME and PATH Variables
      blockinfile:
        path: '/etc/profile'
        insertafter: 'EOF'
        block: |2
          
          # Setting up JAVA_HOME
          export JAVA_HOME=/usr/lib/jvm/java
          
          # Setting up HADOOP_HOME
          export HADOOP_HOME={{ HADOOP_HOME }}
          
          # Setting up HADOOP_CONF_DIR
          export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
          
          # Adding JAVA & HADOOP Binaries to PATH Variable
          export PATH=$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

        state: present
        backup: true

    - name: Checking mapred-site.xml.template
      stat:
        path: '{{ HADOOP_HOME }}/etc/hadoop/mapred-site.xml.template'
      register: file_status

    - name: Renaming mapred-site.xml.template to mapred-site.xml
      command: mv {{ HADOOP_HOME }}/etc/hadoop/mapred-site.xml.template {{ HADOOP_HOME }}/etc/hadoop/mapred-site.xml
      when: file_status.stat.exists

    - name: Configuring mapred-site.xml
      blockinfile:
        path: '{{ HADOOP_HOME }}/etc/hadoop/mapred-site.xml'
        insertafter: <configuration>
        block: |2
              <property>
                  <name>mapreduce.framework.name</name>
                  <value>{{ HADOOP_MAPREDUCE_FRAMEWORK_NAME }}</value>
              </property>
              <property>
                  <name>mapreduce.job.tracker</name>
                  <value>{{ hostname_fqdn.stdout }}:9001</value>
              </property>
              <property>
                  <name>mapreduce.jobhistory.webapp.address</name>
                  <value>{{ hostname_fqdn.stdout }}:19888</value>
              </property>
              <property>
                  <name>yarn.nodemanager.resource.memory-mb</name>
                  <value>{{ HADOOP_YARN_NODEMANAGER_RESOURCE_MEMORY_MB }}</value>
              </property>
              <property>
                  <name>yarn.scheduler.maximum-allocation-mb</name>
                  <value>{{ HADOOP_YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB }}</value>
              </property>
              <property>
                  <name>yarn.scheduler.minimum-allocation-mb</name>
                  <value>{{ HADOOP_YARN_SCHEDULER_MINIMUM_ALLOCATION_MB }}</value>
              </property>
              <property>
                  <name>yarn.nodemanager.vmem-check-enabled</name>
                  <value>{{ HADOOP_YARN_NODEMANAGER_VMEM_CHECK_ENABLED }}</value>
              </property>
              <property>
                  <name>yarn.app.mapreduce.am.resource.mb</name>
                  <value>{{ HADOOP_YARN_APP_MAPREDUCE_AM_RESOURCE_MB }}</value>
              </property>
              <property>
                  <name>yarn.app.mapreduce.am.command-opts</name>
                  <value>{{ HADOOP_YARN_APP_MAPREDUCE_AM_COMMAND_OPTS }}</value>
              </property>
              <property>
                  <name>mapreduce.map.cpu.vcores</name>
                  <value>{{ HADOOP_MAPREDUCE_MAP_CPU_VCORES }}</value>
              </property>
              <property>
                  <name>mapreduce.reduce.cpu.vcores</name>
                  <value>{{ HADOOP_MAPREDUCE_REDUCE_CPU_VCORES }}</value>
              </property>
        state: present
        backup: true
      notify: restart mr history server service

    - name: Creating MR History Server systemd service file
      file:
        path: '{{ HADOOP_MR_HISTORY_SERVER_SERVICE_FILE }}'
        state: touch
        owner: root
        group: root
        mode: 0644

    - name: Configuring MR History Server service as systemd service
      copy:
        dest: '{{ HADOOP_MR_HISTORY_SERVER_SERVICE_FILE }}'
        content: |
          [Unit]
          Description=Hadoop MR History Server Service
          
          [Service]
          Type=forking
          Environment=JAVA_HOME=/usr/lib/jvm/java
          Environment=HADOOP_HOME={{ HADOOP_HOME }}
          Environment=HADOOP_CONF_DIR={{ HADOOP_HOME }}/etc/hadoop 
          ExecStart={{ HADOOP_HOME }}/sbin/mr-jobhistory-daemon.sh start historyserver
          ExecStop={{ HADOOP_HOME }}/sbin/mr-jobhistory-daemon.sh stop historyserver
          
          [Install]
          WantedBy=multi-user.target

    - name: Start MR History Server Service
      systemd:
        daemon_reload: true
        enabled: true
        name: mrhistoryserver
        state: started

  handlers:
    - name: restart mr history server service
      service:
        name: mrhistoryserver
        state: restarted
