apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.active_instance_name }}
spec:
  type: {{ .Values.service.port_type }}
  selector:
    app: {{ .Values.active_instance_name }}
  ports:
  - port: {{ .Values.container.ports.container_port }}
    targetPort: {{ .Values.service.ports.target_port }}
    nodePort: {{ .Values.service.ports.active_port }}
