---
- name: Add http firewall rule
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: Add https firewall rule
  firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled