---
  - name: install-apache-server-playbook
    hosts: myservers1
    become: yes

    vars:
      input_msg: 'World'
      web_server_name: 'httpd'

    tasks:
      - name: Ensure Apache Server is at the latest version
        yum:
          name: httpd
          state: latest
      
      - name: Ensure Apache Server is running
        service:
          name: httpd
          state: started

      - name: Copy index.html
        copy:
          src: index.html
          dest: /var/www/html/
          owner: root
          group: root
          mode: 0644
        notify: restart apache

      - name: Replace web page with Input Message
        replace:
          path: /var/www/html/index.html
          regexp: 'INPUT_MESSAGE'
          replace: '{{ input_msg }}'
        notify: restart apache

      - name: Replace web page with Server Name
        replace:
          path: /var/www/html/index.html
          regexp: 'WEB_SERVER_NAME'
          replace: '{{ web_server_name }}'
        notify: restart apache

      - name: Add http firewall rule
        firewalld:
          service: http
          permanent: yes
          state: enabled

      - name: Add https firewall rule
        firewalld:
          service: https
          permanent: yes
          state: enabled
    handlers:
      - name: restart apache
        service:
          name: httpd
          state: restarted
