apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-world
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: hello-external-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
